name: Cleanup PR Preview
on:
  pull_request:
    types: [closed]
    paths: [ website/** ]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          role-to-assume: arn:aws:iam::${{ vars.CD_BETA_ACCOUNT }}:role/${{ vars.RELEASE_ROLE_NAME }}
          aws-region: ${{ vars.AMPLIFY_REGION }}
      
      - name: Delete Amplify branch and S3 files
        run: |
          BRANCH_NAME="pr-${{ github.event.number }}"
          
          # Delete the Amplify branch
          echo "Deleting Amplify branch: $BRANCH_NAME"
          if aws amplify get-branch --app-id ${{ vars.AMPLIFY_APP_ID_BETA }} --branch-name "$BRANCH_NAME" 2>/dev/null; then
            aws amplify delete-branch --app-id ${{ vars.AMPLIFY_APP_ID_BETA }} --branch-name "$BRANCH_NAME"
            echo " Deleted Amplify branch: $BRANCH_NAME"
          else
            echo " Branch $BRANCH_NAME not found or already deleted"
          fi
          
          # Delete S3 files for this PR
          echo "Cleaning up S3 files for PR #${{ github.event.number }}"
          aws s3 rm s3://${{ vars.AMPLIFY_S3_BUCKET_BETA }}/pr-${{ github.event.number }}/ --recursive
          echo "Cleaned up S3 files for PR #${{ github.event.number }}"
