name: Deploy Preview to Amplify
on:
  pull_request:
    branches: [ main ]
    # paths: [ website/** ]

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Install Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: test/hack/resource/go.mod
          check-latest: true
          cache-dependency-path: "test/hack/resource/go.sum"
      - name: Install Hugo
        uses: peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d # v2.6.0
        with:
          hugo-version: '0.120.3'
          extended: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          role-to-assume: arn:aws:iam::${{ vars.CD_BETA_ACCOUNT }}:role/${{ vars.RELEASE_ROLE_NAME }}
          aws-region: ${{ vars.AMPLIFY_REGION }}
      - name: Get preview URL
        id: preview
        run: |
          BRANCH_NAME="pr-${{ github.event.number }}"
          APP_DOMAIN=$(aws amplify get-app --app-id ${{ vars.AMPLIFY_APP_ID_BETA }} --query 'app.defaultDomain' --output text)
          PREVIEW_URL="https://$BRANCH_NAME.$APP_DOMAIN"
          echo "url=$PREVIEW_URL" >> $GITHUB_OUTPUT
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
      - name: Build Hugo site (deploy-preview context)
        working-directory: website
        env:
          HUGO_ENV: production
          HUGO_ENABLEGITINFO: true
          TZ: America/Los_Angeles
          HUGO_CACHEDIR: ${{ github.workspace }}/.hugo
          NPM_CONFIG_CACHE: ${{ github.workspace }}/.npm
        run: |
          npm ci --prefer-offline
          hugo --gc --minify --buildFuture -b "${{ steps.preview.outputs.url }}"
      - name: Upload to S3
        run: |
          aws s3 sync website/public/ s3://${{ vars.AMPLIFY_S3_BUCKET_BETA }}/pr-${{ github.event.number }}/ --delete
      - name: Create Amplify branch (if doesn't exist)
        run: |
          if ! aws amplify get-branch --app-id ${{ vars.AMPLIFY_APP_ID_BETA }} --branch-name "${{ steps.preview.outputs.branch }}" 2>/dev/null; then
            aws amplify create-branch \
              --app-id ${{ vars.AMPLIFY_APP_ID_BETA }} \
              --branch-name "${{ steps.preview.outputs.branch }}" \
              --description "Preview for PR #${{ github.event.number }}"
          fi
      - name: Configure redirects
        run: |
          REDIRECT_RULES=$(python3 .github/scripts/parse-redirects.py)
          aws amplify update-app \
            --app-id ${{ vars.AMPLIFY_APP_ID_BETA }} \
            --custom-rules "$REDIRECT_RULES"
      - name: Deploy to Amplify
        run: |
          aws amplify start-deployment \
            --app-id ${{ vars.AMPLIFY_APP_ID_BETA }} \
            --branch-name "${{ steps.preview.outputs.branch }}" \
            --source-url "s3://${{ vars.AMPLIFY_S3_BUCKET_BETA }}/pr-${{ github.event.number }}/" \
            --source-url-type BUCKET_PREFIX
      - name: Comment on PR
        run: |
          gh pr comment ${{ github.event.number }} --body "**Preview deployment ready!**

          **Preview URL:** ${{ steps.preview.outputs.url }}

          Built from commit \`${{ github.event.pull_request.head.sha }}\`

          This preview will update automatically with new commits."
        env:
          GH_TOKEN: ${{ github.token }}
